import Head from 'next/head'
import ProductDetailModulel from '../../src/modules/product-detail'

export default function ProductDetails() {
  return (
    <div>
      <Head>
        <title>Mỹ phẩm - Chi Tiết</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetailModulel />
    </div>
  )
}   
