import Head from "next/head";
import ProductModule from "../../src/modules/product";

export default function Product() {
  return (
    <div>
      <Head>
        <title>Mỹ phẩm - Sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductModule />
    </div>
  );
}
