import Head from 'next/head'
import CartModule from '../src/modules/cart'

export default function ProductDetails() {
  return (
    <div>
      <Head>
        <title>Mỹ phẩm - Giỏ hàng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartModule />
    </div>
  )
}
