import Head from 'next/head'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Mỹ phẩm - Chi Tiết</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full flex justify-center items-center">
        Liên hệ
      </div>
    </div>
  )
}
