import Head from 'next/head'
import ContactModule from '../src/modules/contact'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Mỹ phẩm - Liên hệ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactModule />
    </div>
  )
}
